var annotated_dup =
[
    [ "EmbeddedLogger", null, [
      [ "ILogTarget", "classEmbeddedLogger_1_1ILogTarget.html", null ],
      [ "Logger", "classEmbeddedLogger_1_1Logger.html", "classEmbeddedLogger_1_1Logger" ],
      [ "SerialLogger", "classEmbeddedLogger_1_1SerialLogger.html", null ],
      [ "SerialWirelessLogger", "classEmbeddedLogger_1_1SerialWirelessLogger.html", null ],
      [ "WirelessLogger", "classEmbeddedLogger_1_1WirelessLogger.html", null ]
    ] ],
    [ "Buggy", "classBuggy.html", "classBuggy" ],
    [ "BuggyState", "classBuggyState.html", null ],
    [ "BuggyWiFi", "classBuggyWiFi.html", "classBuggyWiFi" ],
    [ "BuggyWifi", "classBuggyWifi.html", null ],
    [ "CalibrationState", "classCalibrationState.html", null ],
    [ "CommandPacket", "structCommandPacket.html", "structCommandPacket" ],
    [ "ControlPacket", "structControlPacket.html", null ],
    [ "DrivingStraightState", "classDrivingStraightState.html", null ],
    [ "IdleState", "classIdleState.html", null ],
    [ "IrSensor", "classIrSensor.html", "classIrSensor" ],
    [ "LineFollower", "classLineFollower.html", "classLineFollower" ],
    [ "LineFollowingState", "classLineFollowingState.html", null ],
    [ "LogPacket", "structLogPacket.html", null ],
    [ "Matrix", "classMatrix.html", null ],
    [ "MotorDriver", "classMotorDriver.html", "classMotorDriver" ],
    [ "MotorPinGroup", "structMotorPinGroup.html", "structMotorPinGroup" ],
    [ "MoveMeanFilter", "classMoveMeanFilter.html", null ],
    [ "ObjectDetectedHandlerState", "classObjectDetectedHandlerState.html", null ],
    [ "ObjectDetectedState", "classObjectDetectedState.html", null ],
    [ "Packet", "structPacket.html", "structPacket" ],
    [ "PacketContent", "unionPacketContent.html", "unionPacketContent" ],
    [ "PacketDeserializer", "classPacketDeserializer.html", null ],
    [ "PacketFactory", "classPacketFactory.html", null ],
    [ "PacketSerializer", "classPacketSerializer.html", null ],
    [ "PIDConstants", "structPIDConstants.html", null ],
    [ "PIDController", "classPIDController.html", "classPIDController" ],
    [ "StatusPacket", "structStatusPacket.html", "structStatusPacket" ],
    [ "TcpServer", "classTcpServer.html", "classTcpServer" ],
    [ "UltrasonicSensor", "classUltrasonicSensor.html", "classUltrasonicSensor" ],
    [ "UltrasonicSensorPinGroup", "structUltrasonicSensorPinGroup.html", "structUltrasonicSensorPinGroup" ]
];